%  p1=[];
%  p2=[];
H2to1=computeH(p1',p2');
out_size=[160 120];
% img=imread('Original.jpg');
%img=uint8(zeros(160,120,3));
img1=warpH(img, H2to1, out_size, 0);
% vid=videoinput('winvideo',2,'YUY2_160x120');
% imgNew=getsnapshot(vid);
imgNew1=warpH(imgNew, H2to1, out_size,0);
%img=imread('Original.jpg');
%imgNew=imread('New.jpg');
imgChange=imgNew1-img1;
imgGray=rgb2gray(imgChange);
% % imgGray=imgGray+40;
% imgBw=im2bw(imgGray,graythresh(imgGray));
% %0.01;
% %0.08
imgBw=im2bw(imgGray,0.01);
% imgR=im2bw(imgNew1(:,:,1),graythresh(imgGray));
% imgG=im2bw(imgNew1(:,:,2),graythresh(imgGray));
% imgB=im2bw(imgNew1(:,:,3),graythresh(imgGray));
% imgR=im2bw(imgNew1(:,:,1),0.6);
% imgG=im2bw(imgNew1(:,:,2),);
% imgB=im2bw(imgNew1(:,:,3),);
% imgBw=imgR|imgB|imgG;
imgErode=imerode(imgBw,strel('disk',3));
LB = 100;
IL = bwlabel(imgErode);
R = regionprops(imgErode,'Area');
area=cat(1,R.Area);
[areaSorted,ind]=sort(area,'descend');
%ind = find([R.Area] >= LB);
indNew=[ind(1) ind(2)];
Iout = ismember(IL,indNew);
figure,imshow(Iout);
C=regionprops(imgErode,'Centroid');
%C=regionprops(Iout,'Centroid');
centroid=cat(1,C.Centroid);
centerP=C(ind(1),:).Centroid;
centerA=C(ind(2),:).Centroid;
centerPw=[(89-centerP(2))*(25/3),(centerP(1)-46)*7.3 ]
centerAw=[(89-centerA(2))*(25/3),(centerA(1)-46)*7.3 ]
% se=serial('COM8','BaudRate',9600);
% fopen(se);
% strX=strcat('xa',num2str(center(1)*4),'$');
% strY=strcat('ya',num2str(center(2)*4),'$');
% fwrite(se,strX);
% fwrite(se,strY);
% fclose(se);